[package]
name = "day1_rust"
version = "0.1.0"
authors = ["Sam Little <kagutaba256@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
